version '3.7'

services:
  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      